global:
  sendAnonymousUsage: false
api:
  insecure: false
  dashboard: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  wings:
    address: ":8080"
providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: pterodactyl

