name: Build & Push Wings

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./build/wings
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/birarustudios/development/wings:latest
            ghcr.io/birarustudios/development/wings:sha-${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/birarustudios/development/wings:latest
          cache-to: type=registry,mode=max,ref=ghcr.io/birarustudios/development/wings:latest
